### ISSUE TITLE
Prevent map zooming out and re-centering after turning filters on or off

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#100]
Another disconcerting map pan and zoom experience is that the map reloads when setting or clearing filters
Sometimes I have found it runs through the initial map cycle and first centers on Central Park - but usually it just zooms out and recenters.

- [x] When turning a filter on or off, the map should reload without zooming out

**Comment by doobneek1** [comment]
it is still moving around wen you remove filters
