### ISSUE TITLE
Fix Menu back button when in the Explore services sub menu

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#103]
- [ ] If clicking the menu back button when in the 'Explore services' part of the menu, you should be taken back to the primary menu
Currently the back button closes the menu

https://github.com/streetlives/streetlives_v2/assets/13530245/5ba96f1b-6245-4be3-bf11-222279cd7e52

**Comment by doobneek1** [comment]
@jbeard4 it is not fixed
