### ISSUE TITLE
Unable to delete data from gogetta fields

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#109]
Steps to recreate:
I was working in [this field](https://test.gogetta.nyc/team/location/46ebeeaa-f8fa-48b9-855c-657ef529456a/questions/location-name)
- I deleted the location name on test.gogetta /team. It appeared to work fine
- I went to [test.yourpeer](https://test.yourpeer.nyc/locations/test-bay-ridge-area-bay-ridge), refreshed the page and saw the location name had gone. 
- I went back to gogetta / team Within a few seconds the red footer appeared
- I went back to test.yourpeer, refreshed, and saw that the location name had re-appeared.
- I deleted the location name once again on test.gogetta /team, Again it appears to work fine. No red footer appeared
- This time though, even though the location name field on test.gogetta remained blank, test.yourpeer retained the location name
- Returning to test.gogetta /find, the red footer has returned and the “loading location data” wheel is spinning

**Comment by doobneek1** [comment]
@adambard1 It is not a problem anymore, although the red bar still exists, I refresh and ensure my deletion worked, it generally words for 1st or 2nd time in all fields
