### ISSUE TITLE
Shelter filters: Incorrect locations identified. Fix location information to enable functioning filters

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#147]
- [x] Family **must** identify:

[DHS PATH intake](https://gogetta.nyc/team/location/2c12395c-ae45-40d5-94e3-4db35c7ce823)
[DHS AFIC intake](https://gogetta.nyc/team/location/a75bd017-3765-4298-9e32-1957b46c623b)

- [ ] Family **should probably not** identify

[SCO Family of Services (Brooklyn DYCD Youth Drop-in Center)](https://gogetta.nyc/find/Shelter/location/0aeaeca9-4c98-406b-8cc6-81974c659ba4)
[United Bronx Parents, Inc. (Acacia Network)](https://gogetta.nyc/find/Shelter/location/a6640482-5d4d-425b-88d4-c6da1a5d2b37)

- [ ] Single Adult **maybe shouldn't** identify:

[Covenant House (Northern New Jersey)](https://gogetta.nyc/find/Shelter/location/e26dbb99-2732-4007-aa10-b9dd57c94876)
[Violence Intervention Program (VIP) Community Services](https://gogetta.nyc/find/Shelter/location/639a7b12-c0ac-40b6-973f-5cfeaf15065a)
Or, if it should, then we should create all the Youth Shelter locations as Adult locations. Obv it's annoying that there is an overlap for ages 18-25

"Any" should probably not identify... (tbd- AB to confirm with Specialists)

**Comment by doobneek1** [comment]
@adambard1 I do not recollect what we agreed to so the items you said "maybe" to are not clear to me. The family filter is not correctly identifying shelters

**Comment by adambard1** [comment]
> @adambard1 I do not recollect what we agreed to so the items you said "maybe" to are not clear to me. The family filter is not correctly identifying shelters

@doobneek1 I just meant I don't know if
[Covenant House (Northern New Jersey)](https://gogetta.nyc/find/Shelter/location/e26dbb99-2732-4007-aa10-b9dd57c94876)
[Violence Intervention Program (VIP) Community Services](https://gogetta.nyc/find/Shelter/location/639a7b12-c0ac-40b6-973f-5cfeaf15065a)
are Single Adult shelters.

The family shelter issue is being fixed.

There may be some issues where shelters are created using the wrong default button (e.g., they create an adult shelter using the youth button), then the service name gets changed and we can't tell that it's wrong until it shows up in the wrong filter

**Comment by doobneek1** [comment]
@adambard1 I think we need a new category of youth and young adult runaway homeless shelter or something to that effect

**Comment by adambard1** [comment]
Just reopening this to help us with the new categories and for info for @saumyaphadkar24
