### ISSUE TITLE
Open service accordion for selected category services when clicking into location details

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#149]
e.g. https://test.yourpeer.nyc/locations/department-of-homeless-services-dhs-manhattan
test opens with the accordion closed
<img width="714" alt="Screenshot 2024-02-21 at 17 37 24" src="https://github.com/streetlives/streetlives_v2/assets/13530245/5a023789-3ffb-4ea4-9805-f2e3a8c3b541">

but should open the service, as in live
<img width="559" alt="Screenshot 2024-02-21 at 17 38 02" src="https://github.com/streetlives/streetlives_v2/assets/13530245/76ba98d2-9f06-47dd-b2f2-4a71c207d0ce">

**Comment by doobneek1** [comment]
@adambard1 seems to be fixed if you are talking about line break formatting
