### ISSUE TITLE
how do we deal with http://www. sites links?

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#150]
Create, Inc. has 3 locations
https://gogetta.nyc/find/location/6f3e13c5-92a4-4b17-8191-decdb9921935
https://gogetta.nyc/find/location/427ee11f-771b-49a6-8a6f-2112a24c7166
https://gogetta.nyc/find/location/f4ba0237-801c-49ab-b6f7-75054ec682da
Their site URL is http://www.createinc.org
https://www.createinc.org doesn't work (goes to an error page saying it's an unsupported protocol)
How do we record the URL on the back end to enable a connection?

**Comment by doobneek1** [comment]
@adambard1 I just copy them directly as they are typed in the address field and see on YP if they open or not.

**Comment by adambard1** [comment]
Still an issue - Create inc's website doesn't load from any of the yourpeer locations because its an http site and we automatically provide it as https (and we don't put the scheme on GoGetta).

e.g. [this one](https://test.yourpeer.nyc/locations/create-inc-harlem)
<img width="237" alt="Screenshot 2024-08-20 at 18 12 54" src="https://github.com/user-attachments/assets/7d7f32f1-5be4-470c-94a7-02045142f0ea">

"> @adambard1 I just copy them directly as they are typed in the address field and see on YP if they open or not." Not sure what that means @doobneek1

**Comment by doobneek1** [comment]
@adambard1 ok, I understand now. Nevertheless, the CREATE website opens on production YP when I click, it does not work on test indeed, maybe flag it to the developers?
