### ISSUE TITLE
Format lists in all service information fields

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#153]
e.g. [here](https://test.yourpeer.nyc/locations/destination-tomorrow-dt-bronx)
<img width="640" alt="Screenshot 2024-02-15 at 10 24 12" src="https://github.com/streetlives/streetlives_v2/assets/13530245/2b1ceb6c-dc90-4e2d-843b-2fc1839c2dc3">

- **vs. previous live** which matches the formatting Specialists are creating on GoGetta.

<img width="587" alt="Screenshot 2024-02-15 at 10 26 07" src="https://github.com/streetlives/streetlives_v2/assets/13530245/9e675bc2-aa61-4feb-a1ac-d9659faf1a19">

**Comment by doobneek1** [comment]
@adambard1 done
