### ISSUE TITLE
Use a period as the decimal separator for Spanish translation

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#162]
In the US they use periods before a decimal - [seems most central american countries do too](https://www.smartick.com/blog/other-contents/curiosities/decimal-separators/#:~:text=The%20majority%20of%20European%20countries,which%20uses%20the%20decimal%20point.), whatever the case, we should not mix periods and commas ahead of the decimal, in the screen shot the first location uses a decimal while all others use a comma - and it seems the comma is incorrect if we assume most Spanish speakers in the US are from Central America. So let's remove the distance numbers from the Spanish translation.
Also, not sure what's going on with the first location - is it curtailing the region ("Brookl...") cos the number of characters in the line is long, or cos the heading takes up three lines or something else? none of the other locations curtail the region.

![Screenshot_20231215-103956](https://github.com/streetlives/streetlives_v2/assets/13530245/32065b65-7cd5-4a31-9cf0-423a586ddb97)

**Comment by doobneek1** [comment]
@adambard1 we don't even have distances. Also, when we do, we should offer metric option.
