### ISSUE TITLE
User Sorting of location list

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#164]
@mixedpaper has provided a few selection to sort the list, on the same figma as the H1
I added some designs for this here: https://www.figma.com/file/hE0RcUd4nK4NUe6D62OKR8/YourPeer-V1?type=design&node-id=419%3A6095&mode=design&t=MMwwhTlz1rpcll1N-1

I think it would be good to do different titles for with/without location services. The style for the title should be consistent for searching as well. Let me know what you think.

**Comment by adambard1** [comment]
H1 text is defined here for different modes of operation https://docs.google.com/spreadsheets/d/1CPbCLly8XESaUgqoCgOWwfYPKEuQm5U-qI76M6qu6WY/edit?gid=1799971510#gid=1799971510

**Comment by adambard1** [comment]
This is ready to go after removing the word 'popular' from the Category location presentations, e.g., Health ,here, but the same for all categories?


![Screenshot_20240916-104036](https://github.com/user-attachments/assets/7fbf76b9-6ca6-4a5a-a724-e91465555ec6)

**Comment by shakilhossain1** [comment]
@adambard1 
Fixed. and deployed  [here](https://yourpeer-shakil-ui-issu-nj9kdv.herokuapp.com/) for test

**Comment by adambard1** [comment]
Jake already deployed this last week iirc. Worth checkin on whether you've been duplicating things.
There's an issue with the location details URL which adds the Nearby query to every URL, otherwise it's great.
