### ISSUE TITLE
Missing space in the front page text before Food Policy Center Hyperlink

### ISSUE THREAD

**Issue by doobneek1** [streetlives/yourpeer.nyc#180]
![image](https://github.com/user-attachments/assets/35ae19a3-0fde-4574-98b6-669e7a5c7cc6)
@jbeard4 and @shakilhossain1 can you please add space and remove https://www. part?

**Comment by adambard1** [comment]
Also, I think it should be a normal line return, though I'm not certain.
This is a really simple one, please fix when you have a moment @shakilhossain1
