### ISSUE TITLE
Services without hours are not appearing on YP service details page

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#184]
A regression on YP since refactor is that services without hours are not showing at all on the service detail page, though they do appear on are on the list view

an example is the Future Leaders Program at this location ([gogetta](https://gogetta.nyc/team/location/fcb5fdd7-f54d-4f79-b815-1d61c2d535f6/services/15b4d4d7-11d5-42b7-b33d-eb3d806b7586)) ([yourpeer](https://test.yourpeer.nyc/locations/strive-aka-east-harlem-employment-services-east-harlem))

GoGetta front End
<img width="668" alt="Screenshot 2024-08-16 at 15 56 07" src="https://github.com/user-attachments/assets/85df1b99-1ee2-4498-a6cd-9bec63864031">

**Comment by jbeard4** [comment]
@adambard1 I checked and in the old version of YourPeer, this service would have been marked SUSPENDED. Please see the screenshot below:

![image](https://github.com/user-attachments/assets/b23138fa-d3b7-42e2-aaa4-7fd9950694e8)


Is this the desired behavior, or should it be like YourPeer, where we just show the service? 

![image](https://github.com/user-attachments/assets/c44788c0-ba89-4767-ba7e-be565714ca22)

**Comment by jbeard4** [comment]
Here it is with the fix I've applied: 
![image](https://github.com/user-attachments/assets/01518c54-8c76-45de-a36d-9e3e84deaeb4)

**Comment by jbeard4** [comment]
Fixed on test. Please review.
