### ISSUE TITLE
Check - Gogetta opening hours not shown on YourPeer - service is 'Closed'

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#196]
@doobneek1 fixed this issue but [this location](https://yourpeer.nyc/locations/center-for-the-integration-and-advancement-of-new-americans-ciana-astoria) was showing as closed on YourPeer, even though it had hours and looked fine on [GoGetta.](https://gogetta.nyc/find/location/0b32cf73-5bb3-4916-ae58-59a66444ae9d)

To fix it doobneek edited one of the opening hours in each of the three services.
When the first hour was edited in the first service, the location showed as open, with the hours for open service, but the two other services showed as suspended.
Editing the hours of each service 'opened' the service.

**Comment by adambard1** [comment]
@doobneek1 is there still an issue with services being suspended if hours are removed before changing them (was that the cause of this issue)?

**Comment by doobneek1** [comment]
@adambard1 it's is fixed but @shakilhossain1 is supposed to fix closed services to show red lettering for them.
