### ISSUE TITLE
Cannot unsuspend services on test and live

### ISSUE THREAD

**Issue by doobneek1** [streetlives/yourpeer.nyc#200]
So, I am used to editing hours the following way: if there's a complete change in schedule, I close the service to wipe out all hours and then input new hours instead of editing all buckets one by one. So turns out this suspends the service indefinitely on YP whether it is test or live and when I add new hours, they are displayed on gogetta front end but the service remains closed on YP, I will change my practice from now on, but we have a lot of suspended services that are reopening and this means we cannot reopen them. 
![image](https://github.com/user-attachments/assets/be41bc43-2b42-4004-9852-6c8fcbfd1fbd)
![image](https://github.com/user-attachments/assets/6
![Screenshot 2024-08-31 085850](https://github.com/user-attachments/assets/3f2cb79a-fa11-4d2b-a76c-71a3580c40d2)
9f412c3-c085-4dbb-8af4-2923e8a42ecb)

**Comment by adambard1** [comment]
Just lifting up this bug, it's an important one.

**Comment by adambard1** [comment]
it might be worth checking along with #196 as they seem to have similarity.

**Comment by adambard1** [comment]
@jbeard4 One example is the Food Pantry Service at St. John's Bread & Life
[YourPeer](https://yourpeer.nyc/locations/st-johns-bread-and-life-bedford-stuyvesant) has the Food Pantry Suspended.
<img width="496" alt="Screenshot 2024-09-30 at 12 34 39" src="https://github.com/user-attachments/assets/0d019f03-4128-4386-8188-86417aad8ece">

But [GoGetta has hours showing](https://gogetta.nyc/team/location/1edfab8e-0d7c-437e-a14c-6b9ca0eb5d93/services/299640ce-48a4-4e55-8608-b889ed3160a7/opening-hours). Antoinette fka @doobneek1 said they clicked 'Yes' to Validate the hours were still correct and it suspended the service (without showing a dropdown to view supplemental text, which it should have done if acting as normal)

This is the session info 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/adambard/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/adambard/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


doobneek | St. John's   Bread and Life | Food Pantry | event_related_info, holiday_schedules,   service_languages, service_taxonomy_specific_attributes | 9/11/24 16:44 | https://gogetta.nyc/find/location/1edfab8e-0d7c-437e-a14c-6b9ca0eb5d93 | https://gogetta.nyc/team/location/1edfab8e-0d7c-437e-a14c-6b9ca0eb5d93/services/299640ce-48a4-4e55-8608-b889ed3160a7 | V
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by adambard1** [comment]
Looks like another example is [Juan Newman](https://yourpeer.nyc/locations/juan-newman)'s Immigration Services
Which, likewise, show closed [on YP](https://yourpeer.nyc/locations/juan-newman)
but there are [hours on GoGetta](https://gogetta.nyc/team/location/77429d4e-77bd-4bb9-bd0a-880d4a2a9e0a/services/4332f448-c51a-4c4c-8db3-32d412c34c31/opening-hours)

Session info is here
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/adambard/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/adambard/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Liz24 | Juan Newman |   | Immigration Services | eligibility, event_related_info,   holiday_schedules, required_documents, service_areas, service_languages,   services | 9/25/24 0:19 | https://gogetta.nyc/find/location/77429d4e-77bd-4bb9-bd0a-880d4a2a9e0a | https://gogetta.nyc/team/location/77429d4e-77bd-4bb9-bd0a-880d4a2a9e0a/services/4332f448-c51a-4c4c-8db3-32d412c34c31 | V
-- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
