### ISSUE TITLE
Rephrase View Street View button

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#207]
<img width="294" alt="Screenshot 2024-09-02 at 15 15 05" src="https://github.com/user-attachments/assets/43bc63ce-b829-4bc3-9062-90170166ea0d">

- [x] Rephrase View Street View because it does not translate well and is confusing to people
- suggested: "See Street View" or "Browse Street View"

![image](https://github.com/streetlives/yourpeer.nyc/assets/170349995/571a2bab-238a-4e5a-8704-57dab9dbe4c9)
^Here is how the Google hover words it. doobneek suggests "See how the entrance of this location looks" or something like that. 

(this issue was moved from #56)

**Comment by shakilhossain1** [comment]
@adambard1 
Fixed. and deployed  [here](https://yourpeer-shakil-ui-issu-nj9kdv.herokuapp.com/) for test
