### ISSUE TITLE
Regression on the v1.1 layout on live and staging especially on Details page.

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#212]
Looking at the staging, I realized we've completely lost the 1.1 layout improvements that were implemented and in place before beginning the refactor work in March which came out of the user testing prior to that. @shakilhossain1 had implemented some of these iirc (though I think helena decided not to implement the red quick exit cos it was too distracting).

This is especially clear from the bunched up info on the details page above the service info, where the Phone and website info need some vertical space between them.

Am also curious [in this example](https://staging.yourpeer.nyc/locations/the-bowery-mission-tribeca), where the email info was entered and pulled from?
<img width="340" alt="Screenshot 2024-09-10 at 12 43 13" src="https://github.com/user-attachments/assets/8369e1f2-bd98-44a5-b91d-1486cb933555">

The spacing should be at least like the service details figma wireframes https://www.figma.com/design/lIpuE1FWxJw0At3mJ1gvl6/YourPeer-V1.1?node-id=140-2509&t=2o46Mm2MSC6d0Dok-1
idk what happened to the 'Suggest Edit' button, which looks unfinished to me since the icon is so large

<img width="405" alt="Screenshot 2024-09-10 at 12 45 48" src="https://github.com/user-attachments/assets/6d01c721-951c-4a7f-9445-3814d067b898">

and also see the list view and map with filter wireframes https://www.figma.com/design/lIpuE1FWxJw0At3mJ1gvl6/YourPeer-V1.1?node-id=342-864&t=2o46Mm2MSC6d0Dok-1

Note these allowed for the distance from the user to be shown, having implemented the location sorting.

We really need to work on our institutional memory regarding things like this. I am as guilty as others, but particularly if you have already implemented some changes, we mustn't lose them in our fixes through lack of checking in with each other. Do you recall @shakilhossain1 @dilu2024 how far we'd gotten with these?

**Comment by shakilhossain1** [comment]
@adambard1 
Fixed. and deployed  [here](https://yourpeer-shakil-ui-issu-nj9kdv.herokuapp.com/) for test
