### ISSUE TITLE
Clear search issue - manual deletion of search field does not clear the search term

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#221]
Currently if I search and then manually delete the search term rather than use the X, The map does not clear.
The cause of the issue is that the query remains until either another search is created and someone eventually uses the x.

- [x] Is there a way for manual delete to clear the search query in the same way the X does?

**Searching**
<img width="1090" alt="Screenshot 2024-09-23 at 13 19 29" src="https://github.com/user-attachments/assets/5f20f23b-3bb1-41ba-b8e5-511de5ceee80">

**Manually deleted but query still has the term**
<img width="1090" alt="Screenshot 2024-09-23 at 13 19 17" src="https://github.com/user-attachments/assets/537bf9e6-23c7-4fc8-a6ff-15dd2acda8dc">

**Comment by shakilhossain1** [comment]
@adambard1,
Here's the fix for this issue

https://yourpeer-shakil-fix-tit-2omvai.herokuapp.com/
