### ISSUE TITLE
Fix Title tags please - they are only showing neighborhoods

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#223]
Please fix the regression on Title tags, they aren't showing the location info.

[The IA defines them in col G](https://docs.google.com/spreadsheets/d/1fWWPiQI1IFWkzOlgBHFU3f_2oDcKUe1wl37zQney7Zo/edit?gid=1722854430#gid=1722854430).
For general locations they will be 

[Location name] in [Area i.e. Bronx] | YourPeer

Example: 
Ali Forney Center in Hell's Kitchen | YourPeer

And we don't want the preview to be just the neighborhood.
<img width="362" alt="Screenshot 2024-09-23 at 17 47 09" src="https://github.com/user-attachments/assets/9ecf1049-3c2b-4ba3-bfea-6c3d6fb7e7bc">

**The title tags we set up to group certain types of locations are working**
![PXL_20240923_213751873](https://github.com/user-attachments/assets/9769b890-154d-4e93-9fd5-23b68204cf7f)

**but individual location's title tags aren't.**
![PXL_20240923_213757085](https://github.com/user-attachments/assets/f4ac695f-effa-4551-aa37-5c69606abd8a)

**Comment by adambard1** [comment]
Hi @shakilhossain1 I'm elevating this to high prio cos it's affecting how google is understanding the page. Please fix this asap.

**Comment by shakilhossain1** [comment]
@adambard1  
Here's the fix for the title tags
https://yourpeer-shakil-fix-tit-2omvai.herokuapp.com
