### ISSUE TITLE
Enable crawlability of Off Canvas Menu

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#251]
Problem: the OffCanvasMenu is not crawlable. This is particularly important because it contains the service subcategories (e.g. https://yourpeer.nyc/shelters-housing/adult), so the service subcategories have not been getting crawled by Google.

The reason for this is that the OffCanvasMenu is not being rendered into the DOM on page load - it requires a button click on the hamburger menu for it to render into the DOM.

Solution: @shakilhossain1 can you please change the implementation so that the OffCanvasMenu gets rendered into the DOM on page load, but is hidden with CSS (e.g. display:none) until the user clicks the button. This way Google should be able to crawl the menu.

**Comment by adambard1** [comment]
@shakilhossain1 how's the status on this?

**Comment by shakilhossain1** [comment]
it's fixed.

**Comment by jbeard4** [comment]
@shakilhossain1 Any update on this?

**Comment by jbeard4** [comment]
Ran screaming frog, confirmed this is working.
