### ISSUE TITLE
Provide access to Alnisha Maniaci alnisha.maniaci@pwpllchq.com for data analysis

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#254]
It'll be access to the APIs and Big Query I expect. Lmk if I need to do anything

**Comment by jbeard4** [comment]
Google seems to dislike this email address. @adambard1 Is there one we can use which is associated with a Google account?

![image](https://github.com/user-attachments/assets/c9366f4d-1b1b-4cfa-96da-cff318665f11)

**Comment by adambard1** [comment]
Let's see what she gives us.

**Comment by jbeard4** [comment]
I sent an email. Standing by to hear back.
