### ISSUE TITLE
Correction to Terms of Use Policy

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#36]
I noticed an error in the Terms of Use

- [x] The footnote on the policy to the Governing Law clause has been posted in the Dispute Resolution clause. Please amend this and clarify the footnote with a superscript footnote marker after the period following "Governing Law." [as in the source document](https://docs.google.com/document/d/1EJO7Hck4DRsOWysRA2RQomUC0W5EfjuW/edit) (bottom of p3)
- [x] Then change the "Last updated" date to the date of the correction.

Existing Incorrect footnote position
<img width="340" alt="Screenshot 2024-08-06 at 10 06 31" src="https://github.com/user-attachments/assets/68d6d747-c436-4d28-b96e-346a7fa03cda">

**Comment by adambard1** [comment]
- [x] Foot note is to Clause 10, not Clause 11.
- [x] Footnote superscipt goes after the period that the note applies to and has a space before the nesxt sentence.

### Original document
<img width="346" alt="Screenshot 2024-08-19 at 19 17 13" src="https://github.com/user-attachments/assets/6e42834b-3069-4bf1-9e24-feadce846155">

### Online errors
<img width="748" alt="Screenshot 2024-08-19 at 19 17 52" src="https://github.com/user-attachments/assets/6496414f-1763-4baf-932d-a4e547218429">

**Comment by adambard1** [comment]
Please can we fix this @shakilhossain1

**Comment by doobneek1** [comment]
@adambard1, this is not fixed. Why was it moved to QA? @shakilhossain1 the date is Aug 9, not 6, I also recommend moving the footnote itself to the very end of the document after the date as we do not have a page breakdown, or put the footnote right after the 10th point as it pertains to it.

**Comment by shakilhossain1** [comment]
"1. Implications of choice of law should be discussed with the client—it is important to explain why choosing their home state may be most beneficial."

put this paragraph to clause 10

**Comment by adambard1** [comment]
Please do this @shakilhossain1 nd add the date that the policy was last updated as we have at the top of the Privacy Policy, which would be Aug 6 or 7 for the Terms of Use, given the date of this ticket.

**Comment by doobneek1** [comment]
@shakilhossain1 when will you move the footnote to the end of the doc or at the bottom of 10th point?

**Comment by jbeard4** [comment]
@ryanstpierre  Can you pick this up?

**Comment by jbeard4** [comment]
LGTM

**Comment by jbeard4** [comment]
Now deployed to https://test.yourpeer.nyc/terms-of-use

**Comment by doobneek1** [comment]
@jbeard4 ![Image](https://github.com/user-attachments/assets/bef88d75-41aa-4d07-a773-61ae150959a1)
This hyperlink for footnote scrolls passed footnote; let's just remove this bookmark and not make it clickable.
