### ISSUE TITLE
Refactor: Language selection disappears from homepage when returning to the page

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#38]
- [x] Make language selection persist on homepage

It isn't regularly visible once leaving it.
Here, the language selection appears on the first return to homepage but not on the second.
Same issue for desktop and mobile

https://github.com/user-attachments/assets/e8180508-219b-4bf7-8ccb-9861d92e73c4

**Comment by doobneek1** [comment]
@jbeard4 I want language selection to be available on all pages.

**Comment by doobneek1** [comment]
fixed otherwise
