### ISSUE TITLE
Make sure users are prompted to install the PWA

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#39]
On chrome android I am not being asked to install the PWA even though it is not one of my apps.
This is a regression from all previous versions.
I don't know what the installation dialogue window looks like but, if it's an option, if people decline to install the PWA three times then we can stop offering it.

**Comment by doobneek1** [comment]
No popup but it can be installed from a dropdown menu

**Comment by doobneek1** [comment]
@jbeard4 not fixed

**Comment by shakilhossain1** [comment]
it depend on some device, for some specific device it won't work.

**Comment by adambard1** [comment]
This isn't working at the moment - if you are on yourpeer on mobile it should suggest adding it to the desktop

**Comment by adambard1** [comment]
Works.
