### ISSUE TITLE
Loading messages appear between filter selections

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#41]
The loading messages didn't appear before. Perhaps they can be replaced by the [loading animation](https://github.com/streetlives/yourpeer.nyc-nextjs/issues/80) if they are going to be a constant.

https://github.com/user-attachments/assets/ee554276-f17f-4dac-b427-28f703608b7c

**Comment by doobneek1** [comment]
it seems to have been fixed, especially for the phone.
