### ISSUE TITLE
Nextjs refactor: Show the location and Quick exit buttons in the location details header when scrolling

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#44]
Match the production behavior for the header on the location details page.

https://github.com/user-attachments/assets/2ecdaa95-1851-4cff-a65a-80c7ea946d55

Heroku behavior

https://github.com/user-attachments/assets/04d688ad-1b35-4fa2-8bff-15a5757d6e5f

**Comment by doobneek1** [comment]
@adambard1  this is done
