### ISSUE TITLE
Nextjs refactor: Reinstate documents required and age eligibility information

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#45]
Documents required and Age are missing from [this instance](https://yourpeer-f5f080230d56.herokuapp.com/)
e.g. for "The Door"
Heroku
<img width="338" alt="Screenshot 2024-07-17 at 09 44 49" src="https://github.com/user-attachments/assets/bf970490-6260-472e-80b9-f77ebe9e29a4">
Production
<img width="341" alt="Screenshot 2024-07-17 at 09 44 12" src="https://github.com/user-attachments/assets/e9c1263b-5899-464a-b312-64b183f34a23">

**Comment by doobneek1** [comment]
@adambard1 this is done
