### ISSUE TITLE
Fix Word fit on filter screen Button in all languages for narrow screens 

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#51]
This screen is 344x882 (Galaxy Z fold)

<img width="350" alt="Screenshot 2024-07-16 at 17 34 39" src="https://github.com/user-attachments/assets/92409c7d-b85a-4d2d-a68c-3f0088312796">

<img width="353" alt="Screenshot 2024-07-16 at 17 35 52" src="https://github.com/user-attachments/assets/e0665c4f-b2a8-45c8-b579-be99831eb8dd">

**Comment by doobneek1** [comment]
In French I see the same interface as in English @adambard1
