### ISSUE TITLE
Don't allow 'Select Language' to be chosen as an option from the language dropdown menu

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#52]
Disable the selection of 'Select Language'
<img width="331" alt="Screenshot 2024-07-16 at 17 05 37" src="https://github.com/user-attachments/assets/83e5f3dc-231e-42ca-afc4-cbc523e2559a">

**Comment by doobneek1** [comment]
@adambard1 fixed, there is no select language option anymore
