### ISSUE TITLE
Align the Text from the menu bar and the homepage

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#53]
- [ ] The YourPeerNYC and Quick Exit text is slightly higher on the screen in the menu bar than on the homepage. Please match the Homepage "y" position by lowering the text on the menu.

https://github.com/user-attachments/assets/01826a84-1a0c-497f-beac-9f14fc76280e

**Comment by doobneek1** [comment]
@adambard1 fixed
