### ISSUE TITLE
Nextjs  - Fix additional search deletion and operation issues (https://yourpeer-shakil-fix-iss-rhbjp8.herokuapp.com)

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#54]
X is now on the same line, but it only searches and deletes the search term in certain instances

- [x] Enable search terms to be deleted even if they are not executed
- [x] Enable search term deletion on Filter screen
- [x] Apply search term when 'Show results' is pushed if a search term is entered on the Filter screen
- [x] Enable 'no results' message [as here](https://www.figma.com/design/hE0RcUd4nK4NUe6D62OKR8/YourPeer-V1?node-id=38-11030&t=zWIUWEg1xQH0YLB2-1)

Below video shows only the inability to delete the search term if entered but not executed

https://github.com/user-attachments/assets/ee4e83b2-903d-4b8b-bf2a-21c970ac7a90

**Comment by doobneek1** [comment]
@adambard1 it is working, maybe close the issue.
