### ISSUE TITLE
Nextjs refactor: Reduce delay for 'More Details' click through

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#59]
- [ ] On Mobile or desktop, the delay after clicking More Details to get to the Location details page was significant enough to make me think it was broken and tap again a couple of times. I was connected to my wifi but it was the same for 5G.

https://github.com/user-attachments/assets/4a0b7361-f417-4296-bac5-d97ca2293c01

**Comment by doobneek1** [comment]
@adambard1  that is pretty slow still, maybe that warrants the loading animation or else it looks frozen

**Comment by adambard1** [comment]
Still in progress. Should take only fractions of a second.
