### ISSUE TITLE
Nextjs refactor: Enable some form of Age filter visibility on list view

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#62]
<img width="422" alt="Screenshot 2024-07-15 at 11 58 57" src="https://github.com/user-attachments/assets/598a76cf-0051-4378-9dca-c09c04d6610e">
<img width="430" alt="Screenshot 2024-07-15 at 11 59 03" src="https://github.com/user-attachments/assets/b39fe2e9-c487-4a4c-9c06-119a4b51f97f">

**Comment by doobneek1** [comment]
@jbeard4 not done

**Comment by doobneek1** [comment]
@adambard1  I am struggling to understand. I do recollect that if you search by category, currently the service in that category is listed first is is dropped down while other services are collapsed.

**Comment by adambard1** [comment]
This is done - the yellow age pill wasn't showing when the age was entered in the filter.
