### ISSUE TITLE
Update to Privacy Policy

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#70]
[This needs to go up](https://docs.google.com/document/d/1EEPdbflBQxZ6t-F5P9dvQA9TGhqxE7ms/edit) before we begin the next stage of the feedback pilots.

- [x] Change the date at the top to whatever date you upload it.

**Comment by adambard1** [comment]
- [ ] Repost the new policy in its entirety, there are one or two discrepancies in the current version online, which aren't worth covering individually.
- [ ] Change Last Updated to the date you posted the new policy

**Comment by adambard1** [comment]
Hi, please can we get this done? I don't know what the issue is here, @shakilhossain1 - you don't need to know the date of the last update - the text at the top shares the date you upload the new policy, not the previous policy.
So, if you upload it today the text will say "Last Updated September 16, 2024."

**Comment by adambard1** [comment]
Also, could you add some padding between the bottom of the text and the holding hands icon under it
![Screenshot_20240916-102549](https://github.com/user-attachments/assets/3101afd1-8e59-4368-9c03-84e0b2105ad8)

**Comment by adambard1** [comment]
The date change on this policy must be implemented. Please do this asap @shakilhossain1  - it should be the date that it was uploaded, but it has not yet changed from Aug 15, 2023. Let's use June 28, 2024 since that's the day after this issue was first created.

Also please add spaces befor the links in the places below:
### First paragraph
![Image](https://github.com/user-attachments/assets/ec4b78e4-e4c5-40de-b8e5-c85a65afca78)

### Your Choices, second bullet
![Image](https://github.com/user-attachments/assets/d34e3d5e-ee3c-451e-8ac1-d3639d451ed8)


and add a little room at the botom of the policy the request above

**Comment by jbeard4** [comment]
@ryanstpierre  can you pick this up

**Comment by shakilhossain1** [comment]
this is done!
[heruku](https://yourpeer-shakil-privacy-8fxrv8.herokuapp.com/)

**Comment by jbeard4** [comment]
LGTM

**Comment by jbeard4** [comment]
Now deployed to https://test.yourpeer.nyc/privacy-policy

**Comment by adambard1** [comment]
- [ ] Repost the new policy in its entirety, there are one or two discrepancies in the current version online, which aren't worth covering individually.

- [ ] Change Last Updated to the date you posted the new policy

Hi @shakilhossain1 you have fixed the later issues but neither you or jake had completed those checkboxes from August 1. I've added them again here.
Please repost the policy in its entirety, there are some sections that are different from the previous policy.
When you've reposted it, change the date.

**Comment by shakilhossain1** [comment]
https://yourpeer-shakil-update--yz2sn0.herokuapp.com/privacy-policy

@adambard1  can you verify now?

**Comment by adambard1** [comment]
Please add a space after the hyperlink in the Commitment to Children's Privacy clause.
<img width="756" alt="Screenshot 2024-12-02 at 10 02 02" src="https://github.com/user-attachments/assets/9fb78748-31dc-48b5-a067-db53417300c4">

Can we provide hyperlinks in the blue color we use for links in service details?
<img width="408" alt="Screenshot 2024-12-02 at 10 07 09" src="https://github.com/user-attachments/assets/3af0b04f-b67e-46c8-a9ab-411346d1540b">
<img width="756" alt="Screenshot 2024-12-02 at 10 02 02" src="https://github.com/user-attachments/assets/a6faf7ae-a622-4482-a8f6-2bae5f173dd9">


Otherwise all good @shakilhossain1

**Comment by shakilhossain1** [comment]
https://yourpeer-shakil-update--yz2sn0.herokuapp.com/privacy-policy

here's the final.

**Comment by doobneek1** [comment]
Done
