### ISSUE TITLE
Don't clear age filter when selecting or de-selecting the category pill

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#71]
- [ ] When the age filter is chosen on its own, and we move to list view, adding a category by clicking its pill should not clear the age filter. Let age filtering persist until the user turns it off.
- [ ] When the age filter is selected along with a category filter, when we choose to see the number of results and are on list view, clearing the category pill should not clear the age filter.

**Comment by doobneek1** [comment]
@adambard1 this is done
