### ISSUE TITLE
Priortize the selected category in list and detail view - details view prio is broken

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#75]
- [ ] prioritize the selected category in the location details view

Not sure when this broke, I don't think it is to do with the age filter, since it isn't working if no age is entered.
When a user selects a filter category and then clicks into the list to see more details on a result, that category should be top of the list. this is a long established convention for gogetta and yourpeer, helping people in crisis find the service they need.

(This should apply whether the age filter is in operation or not and apply to the list summary as well as the details page).

**Comment by doobneek1** [comment]
@jbeard4 @adambard1 done
