### ISSUE TITLE
Intermittent Trouble selecting category after selecting age in filter

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#76]
- [ ] Check on ability to select categories when using the age filter

This is using a Pixel 7 Pro and Android 14 (latest release)

https://github.com/streetlives/yourpeer.nyc/assets/13530245/7efab976-398d-467d-896f-8aa65c2fd0dd

**Comment by doobneek1** [comment]
@adambard1 cannot reproduce it as well.
