### ISSUE TITLE
Hyperlink YourPeer About Us page to Streetlives website

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#84]
Please hyperlink the logo on the About Us page to https://streetlives.nyc and add the sentence "For more information please see [our website](https://streetlives.nyc)." at the end of the second paragraph so it reads...

We build technology in collaboration with unhoused people, people with lived experience of homelessness, New York social service providers, government, funders, and other system stakeholders in a whole-of-community partnership. For more information please see [our website](https://streetlives.nyc).

**Comment by doobneek1** [comment]
@jbeard4 not done

**Comment by adambard1** [comment]
@shakilhossain1 could you get this done please - should be super simple
![Screenshot_20240916-093748](https://github.com/user-attachments/assets/f0667c1e-2bc0-4f64-8e7f-611ea4db9310)

**Comment by shakilhossain1** [comment]
@adambard1 
Fixed. and deployed  [here](https://yourpeer-shakil-ui-issu-nj9kdv.herokuapp.com/) for test

**Comment by adambard1** [comment]
On the heroku, you haven't added the additional line "For more information [please visit our website](https://www.streetlives.nyc)"

**Comment by shakilhossain1** [comment]
added that line also.

**Comment by doobneek1** [comment]
@adambard1 done but it is not obvious you can click on it, I would make it pop and have a sticker "click here!"
