### ISSUE TITLE
Fix UI for Verification notice on Location Details Page

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#86]
- [x] Service Details page validation checkmark should be green. Match the UI of the list view

The validation check mark on the Location Details page has lost its green color and is now gray.
There is an unnecessary bullet point between the neighborhood and the validation info on the service details page, so it doesn't match the list view.

- CORRECT LIST VIEW neighborhood and validation UI

<img width="420" alt="Screenshot 2024-05-27 at 10 37 26" src="https://github.com/streetlives/yourpeer.nyc/assets/13530245/0e09ccf0-0812-4666-8aae-c4c78ce60bdb">

- INCORRECT LOCATION DETAIL neighborhood and validation UI
<img width="425" alt="Screenshot 2024-05-27 at 10 38 44" src="https://github.com/streetlives/yourpeer.nyc/assets/13530245/6b13e18d-7f1f-44e3-a19c-02e2ad9d4f88">

**Comment by doobneek1** [comment]
@adambard1 done
