### ISSUE TITLE
refactor hmtl code to remove duplicate code

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#93]
@jbeard4 will send a project to @shakilhossain1 

in the meantime @shakilhossain1 please remove unused files

**Comment by doobneek1** [comment]
@adambard1 I do not know how to verify.

**Comment by adambard1** [comment]
Did this happen @jbeard4 @shakilhossain1 ?

**Comment by jbeard4** [comment]
This is an old issue, which pertains to the old yourpeer.nyc-django repository. We accomplished this in the refactor to yourpeer-nextjs, so closing this issue.
