### ISSUE TITLE
Have the map reload in place when clicking Clear all in the filter view

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#99]
related to streetlives/yourpeer.nyc-nextjs#100 
When I am in the filters view and I click the Clear all button, the map initializes - first going to Central Park, then centering on my location, then zooming out

- [x] When clearing all, the only thing that should happen is that the map reloads in place, without zooming out or re-centering

https://github.com/streetlives/streetlives_v2/assets/13530245/93de70c2-a429-45cd-948b-49b12ec5f151

**Comment by doobneek1** [comment]
@jbeard4 not fixed
